packages:
  - apps/*
  - packages/*
allowBuilds:
  "@napi-rs/canvas": true
  "@parcel/watcher": true
  "@scarf/scarf": true
  "@swc/core": true
  argon2: true
  esbuild: true
  protobufjs: true
  sharp: true
  tesseract.js: true
  unrs-resolver: true
